### ISSUE TITLE
4.5 モデリング3のコードについて

### ISSUE THREAD

**Issue by canard0328** [ohmsha/PyOptBook#14]
In [51] 4行目の`x = {}`は`xsm = {}`ではないでしょうか？
`xsm`が宣言済みのため動作に影響はないですが。

**Comment by nnnnishi** [comment]
@canard0328 
指摘のとおりでしたのでgithub上のコードについて修正し、正誤表にも反映しました。
丁寧に読んでいただきありがとうございました。
