### ISSUE TITLE
第5章：配送計画の改善後の定式化について質問があります

### ISSUE THREAD

**Issue by tanemaki** [ohmsha/PyOptBook#18]
はじめまして。書籍、楽しく読ませて頂いてます。

「第5章：配送計画」の改善後の定式化について質問があります。この定式化だと`deliv_count`が0以上であればどのような値でも取れるので、同じ注文（request）を何度も運んでしまうような気がするのですが、この理解で正しいでしょうか？試しに、Jupyter Notebookのコード（`5.routing/routing.ipynb`）を動かして`deliv_count`の値を確認してみると、幾つかの注文に対して`deliv_count`が2以上になっているようです。

また、`deliv_count`を1以下に抑えるような制約を追加すると、`pulp.LpStatus[prob.status]`が`Optimal`から`Infeasible`になってしまい、答えも直感に反するものが出てきてしまいました。

もし、`deliv_count`が2以上になるのが想定内だとすると、ある程度の解を出しておいて、配送済みの注文は後処理で取り除くようにして運用するというのが一つの手となるのでしょうか？

とんちんかんな質問かもしれないのですが、周りに頼れる人もいないので、ここで質問させていただきました。

P.S. 数理最適化は初心者なのですが、この書籍だと順を追って学んでゆけるので、非常に助かっています。ありがとうございます。

**Comment by tanemaki** [comment]
```
plt.plot([v.value() for k, v in deliv_count.items()], 'o-', label='deliv_count')
plt.plot([v.value() for k, v in y.items()], 'x-', label='y')
plt.legend()
```

というコードをJupyter Notebook（`5.routing/routing.ipynb`）のセルに追加して生成した図になります。

![511e7bc2-f9e1-4c13-8ce7-2d24288fa731](https://user-images.githubusercontent.com/3511941/221511711-0c38e7ec-4681-4e23-9744-852208cf12d1.png)

**Comment by kotaishr** [comment]
確認がおそくなり失礼しました。

> 「第5章：配送計画」の改善後の定式化について質問があります。この定式化だとdeliv_countが0以上であればどのような値でも取れるので、同じ注文（request）を何度も運んでしまうような気がするのですが、この理解で正しいでしょうか？

> もし、deliv_countが2以上になるのが想定内だとすると、ある程度の解を出しておいて、配送済みの注文は後処理で取り除くようにして運用するというのが一つの手となるのでしょうか？

はい、いずれもそのとおりです！ (説明があったほうがよかったかもしれません、コメントありがとうございます！)
