### ISSUE TITLE
第7章の誤植について

### ISSUE THREAD

**Issue by tamura-up** [ohmsha/PyOptBook#19]
p.276 の 1 行目

$p1 \geq p2 \geq p3$

は不等号逆ではないかと思います。
(第1版第1刷)

ご確認頂けると幸いです。

**Comment by jiro-iwanaga** [comment]
@tamura-up 
本書をお読みいただきありがとうございます。
ご指摘いただいた点について書籍の誤りでございます。

さっそく[正誤表](https://github.com/ohmsha/PyOptBook/blob/main/%E6%AD%A3%E8%AA%A4%E8%A1%A8.md)を更新しました。
ご連絡いただき感謝致します。

**Comment by tamura-up** [comment]
ご対応ありがとうございます。
確認しましたのでクローズします。
