### ISSUE TITLE
P.60 第3章 要件(7)に関する誤植

### ISSUE THREAD

**Issue by yshr10ic** [ohmsha/PyOptBook#2]
## 指摘事項

P.60の要件(7)の数理モデリングの説明のところで、特定ペアの生徒は同一クラスに割り当てないという要件を以下のように数式で書かれていますが、

![x_{s1, c} + s_{s2, c} \leq 1](https://latex.codecogs.com/gif.latex?x_%7Bs1%2C%20c%7D%20&plus;%20s_%7Bs2%2C%20c%7D%20%5Cleq%201)

正しくは、以下ではないでしょうか？（第2項がxではなくsになっている）

![x_{s1, c} + x_{s2, c} \leq 1](https://latex.codecogs.com/gif.latex?x_%7Bs1%2C%20c%7D%20&plus;%20x_%7Bs2%2C%20c%7D%20%5Cleq%201)

**Comment by jiro-iwanaga** [comment]
@yshr10ic 
誤植のご指摘ありがとうございます。
ご指摘の通り第2項はsではなくxが正しい記述になります。
ご迷惑おかけして申し訳ありません。また、ご指摘に感謝いたします。

さっそく[正誤表](https://github.com/ohmsha/PyOptBook/blob/main/%E6%AD%A3%E8%AA%A4%E8%A1%A8.md)の「本文」のP60に反映させていただきました。

また、本日重版にあたる正誤表の締め切りとなっており、滑り込みで本指摘を反映させられそうです。
重版したタイミングで修正される見込みです。
重ね重ね感謝申し上げます。
