### ISSUE TITLE
ファイル 2.tutorial/tutorial.ipynb に誤植

### ISSUE THREAD

**Issue by jonathanjoster** [ohmsha/PyOptBook#5]
<img width="723" alt="スクリーンショット 2021-12-16 20 57 48" src="https://user-images.githubusercontent.com/53422031/146367571-7d90f85a-d4b0-4cbb-ac2b-1c9587ccf1fa.png">

https://github.com/ohmsha/PyOptBook/blob/main/2.tutorial/tutorial.ipynb

「⑧実装した数理最低聴かモデルのまとめ」ではなく、正しくは「⑧実装した数理最適化モデルのまとめ」です。
テキスト（第1版第2刷）には正しい文面で載っています。

**Comment by jiro-iwanaga** [comment]
@jonathanjoster 
こちらご連絡いただき感謝します。
さっそく対応しました！

**Comment by jonathanjoster** [comment]
@jiro-iwanaga 
対応していただきありがとうございました。
