### ISSUE TITLE
第4章の誤植

### ISSUE THREAD

**Issue by isawa585** [ohmsha/PyOptBook#6]
@jiro-iwanaga @nnnnishi

第4章 割引クーポンキャンペーンの効果最大化

第1版 第1刷の誤植や表記ゆれについてご報告します.

## (1) 誤植

p. 91 下から2行目
誤: 最大する
正: 最大化する

## (2) 表記のゆれ

ゆれ 1: 利用回数, 来店回数
ゆれ 2: 組, 組み合わせ, 組合せ

p. 92 上から2-3行目: 年齢区分と昨年度利用回数区分
p. 92 上から5-6行目: 年齢区分と昨年度利用回数区分の組
p. 94 上から14-15行目: 年齢区分と昨年度利用回数区分の組み合わせ
p. 97 いちばん下の表 および 本文下から2行目: 年齢区分と昨年度来店回数区分
p. 98 下から8行目: 年齢区分と昨年度来店回数区分の組合せ

ゆれ 1 について. 目視で読む限りは, p. 98 以降では, 「来店回数」に統一されているようです.

## (3) 定数とされている量

p. 111 下から2行目
誤: 定数: 会員 $i (\in I)$ がセグメント $s (\in S)$ に属する場合 1、 そうでない場合に 0 となる定数
正: 変数: 会員 $i (\in I)$ がセグメント $s (\in S)$ に属する場合に 1、 そうでない場合に 0 となる変数

**コメント 1**: 「0-1 変数」という用語からもわかるように, Z_{is} の値は変わるため定数とは呼べないのではないでしょうか. Z_{is} を変数と呼ぶことに(決定変数とは区別したいという理由で)抵抗があるようでしたら, 久保幹雄先生の流儀にのっとり, 「パラメータ」と呼ぶのはいかがでしょうか. いずれにしろ, 変更する場合は, p. 112 以降に現れる「定数」という用語にも影響するかと思います.

(参考)
https://orsj.org/wp-content/corsj/or61-10/or61_10_674.pdf

**コメント 2**: p. 105 の破線の枠内の記述にそろえるならば, 「場合」のうしろに助詞「に」が必要です.

同じことが, P_{im}, N_s, C_m にも当てはまり, 添字によって値が変わるため, これらは定数ではありません.

## (4) 表記のゆれ

p. 111

本文では「会員」と書かれているのに対して, コードのコメント文では「顧客」に変わっています.
モデリング 2 (p. 122) でも, 「会員の予算消費期待値」と表記されています.

現状: # (4) 顧客の消費する費用の期待値の合計は100万円以下
こうでは? : # (4) 会員の消費する費用の期待値の合計は100万円以下

## (5) 表記のゆれ

p. 112

本文では, 「会員数」と書かれているのに対して, コードのコメント文では「顧客数」に変わっています.

現状: # 各セグメントとそのセグメントに属する顧客数を対応させる辞書の作成
こうでは?: # 各セグメントとそのセグメントに属する会員数を対応させる辞書の作成

## (6) 誤植

p. 113 下から6行目 (コード中のコメント文)

誤: ...... の 10% 以上送付 
正: ...... の 10% 以上に送付

助詞「に」が抜けています. 本文 (p. 111) では, 正しく「10% 以上に送付」と書かれています.

## (7) 誤植

p. 119 上から1行目

誤: (1) 各会員に対してどのパターンのダイレクトメールを送付するかを決定
正: (1) 各セグメントに対してどのパターンのダイレクトメールを送付するかを決定

## (8) 誤植

p. 119 コードの中のコメント文

誤: # (1) 各会員に対してどのパターンのダイレクトメールを送付するかを決定
正: # (1) 各セグメントに対してどのパターンのダイレクトメールを送付するかを決定

## (9) 誤植

これは3か所あります.

p. 120 上から3行目
p. 120 上から5行目
p. 120 上から11行目 (コード中のコメント文)

誤: (2) 各会員に対して送付するダイレクトメールはいずれか1パターン
正: (2) 各セグメントに対して送付するダイレクトメールはいずれか1パターン

## (10) 誤植

これは3か所あります.

p. 122 上から5行目 (本文)
p. 122 8行目 (破線の囲み枠内)
p. 122 13行目 (コード中のコメント文)

誤: ...... の 10% 以上送付 
正: ...... の 10% 以上に送付

上記の(6)と同様に, 助詞「に」が抜けています.

## (11) 誤植

p. 127 下から9行目
誤: 効果がなく無駄ある
正: 効果がなく無駄である

## (12) 誤植

p. 128 上から4行目と6行目

誤: 
要件 (1) ...... 各会員に対してどのダイレクトメールを送付するかを決定
要件 (2) 各会員に対して送付するダイレクトメールはいずれか1パターン

正:
要件 (1) ...... 各セグメントに対してどのダイレクトメールを送付するかを決定
要件 (2) 各セグメントに対して送付するダイレクトメールはいずれか1パターン

## (13) 誤植

p. 129 上から4行目

誤: 要件 (1) ...... 各会員に対して
正: 要件 (1) ...... 各セグメントに対して

## (14) 誤植

p. 129 上から6-7行目

誤: さきほどまでの各会員に
正: さきほどまでの各セグメントに

## (15) 誤植

これは2か所あります.

p. 129 コード中 (下側の背景が黒色エリア) のコメント文
p. 133 コード中のコメント文

誤: ... 下限値と各会員に対して ...
正: ... 下限値と各セグメントに対して ...

## (16) 誤植

これは3か所あります.

p. 129 コード中 (下側の背景が黒色エリア) のコメント文
p. 133 コード中のコメント文
p. 136 コード中のコメント文

誤: # 会員に対してどのダイレクトメールを送付するか
正: # セグメントに対してどのダイレクトメールを送付するか

## (17) 誤植

これは3か所あります.

p. 131 上から1行目 (コード中のコメント文)
p. 134 上から2行目 (コード中のコメント文)
p. 136 コード中のコメント文

誤: # (2) 各会員に対して ...
正: # (2) 各セグメントに対して ...

## (18) 表記のゆれ

p. 136 コード中のコメント文

現状: # (3) 割引券付与による来客増加数を最大化
こうでは?: # (3) クーポン付与による来客増加数を最大化

それまで一貫して「クーポン」と表記されていましたが, ここでは「割引券」と書かれています.

## (19) 誤植

p. 136 コード中のコメント文

誤:  # (1) 各セグメントへのそれぞれパターンのダイレクトメールの送付率の下限値と各会員に対してどのダイレクトメールを送付するかを決定
正: (コメント自体が不要?)

現状では上のように「送付率の下限値」を決定すると書かれていますが, 本文にあるようにここでは下限は 10% に固定されていて, 計算で求めるわけではないですよね. となると, このコメント自体が不要ではないかと思いました.

## (20) 表記のゆれ および 複数形

p. 138 上から3行目 (コード)

現状: label='Incremental visitor'
修正案: label='Incremental Customers'

p. 138 上から12行目 (コード)

現状: ax1.set_ylabel('Incremental visitor')
修正案: ax1.set_ylabel('Incremental Customers')

誤りとも思わず重要度は低いですが, p. 109 までは会員のことを指すのに, customers.csv や  customer_id と表記されています. もしこの表記に合わせるのであれば, 'Incremental customers' と書くのがより適切かと思いました.

長くなりましたが, ご検討いただけると幸いです. よろしくお願いします.

**Comment by nnnnishi** [comment]
@isawa585
丁寧に読んでいただきありがとうございます。
ご指摘について確認し、また返信させていただきます。

**Comment by isawa585** [comment]
@nnnnishi 

上記 (20) について

よく考えると, 会員数自体が増えたわけではなく, 来店した人が増えたかどうかを示したプロットなので, Visitor(s) で問題ないですね. ここで Customers と書くと会員が増えたのかと誤解する読者が出るおそれがないとは言えません.

いずれにしろ, Visitors と複数形のほうがよいとは思いますが.

そういうわけで, 上記の (20) は, 私としては取り下げたく思います. 失礼いたしました.

**Comment by nnnnishi** [comment]
内容確認いたしました。すべて意図が丁寧にご指摘いただいたおかけでわかりやすかったです。
また、提案の正誤をつけていただいたおかげで正誤表の更新もしやすく、とても助かります。

> (1) 誤植  
> (2) 表記のゆれ  
> (4) 表記のゆれ  
> (5) 表記のゆれ  
> (6) 誤植  
> (10) 誤植  
> (11) 誤植  
> (18) 表記のゆれ  

はご指摘の通りに修正させていただきます。

> (3) 定数とされている量

こちら、Z_{is}は入力データにより変化する値で、ご指摘いただいたとおり「パラメータ」とよぶのは実感にあうのですが、2章などと合わせて「定数」とよんでいます。推察いただいているように、初学者向けの書籍として決定変数とそうでないものを区別しやすくし、かつパラメータという語も理解しづらい読者もいるのでは、ということで「定数」とした、という背景があります。（実は、5章は同じものをパラメータとよんでいるのですが、異なる著者が執筆している箇所について表記を厳密に合わせはしない、と著者同士で決めております。）

コメント2の指摘はそのとおりだと思いますので、反映させていただきます。

```
誤: 会員 $i (\in I)$ がセグメント $s (\in S)$ に属する場合1、
```
```
正: 会員 $i (\in I)$ がセグメント $s (\in S)$ に属する場合に1、
```

> (7) 誤植  
> (8) 誤植  
> (9) 誤植  
> (12) 誤植  
> (13) 誤植  
> (14) 誤植  
> (15) 誤植  
> (16) 誤植  
> (17) 誤植  

要件に紐づく箇所について、執筆の意図としては、（実際にビジネス要件として）課題は「会員に対して」どのクーポンを配信するか決定することではあるものの、モデリングの際には問題規模を縮小するため「セグメントに対して」処理をしているため、モデリング2以降の節も要件については「会員に対して」という表現を残しておりました。実際の処理と要件のコメントが異なる部分で混乱させてしまったかもしれないのですが、こちらはそのままとさせてくださいませ。

> (19) 誤植

以下はご指摘の通りすでに送付率の下限値は決定している、かつ(2)-(5)の要件がコメント中に存在することから(1)を残し、以下のように修正させていただきます。

p. 136 コード中のコメント文7-10行目

誤
```
# (1) 各セグメントへのそれぞれパターンのダイレクトメールの送付率の下限値と各会員に対してどのダイレクトメールを送付するかを決定

# 会員に対してどのダイレクトメールを送付するか
```

正
```
# (1) 各会員に対してどのダイレクトメールを送付するかを決定
```

また、以下も同様のため修正をさせていただきます。

p. 133 コード中のコメント文5-8行目

誤
```
# (1) 各セグメントへのそれぞれパターンのダイレクトメールの送付率の下限値と各会員に対してどのダイレクトメールを送付するかを決定

# 会員に対してどのダイレクトメールをそうするか
```

正
```
# (1) 各会員に対してどのダイレクトメールを送付するかを決定
```

丁寧によんでいただき、かつ正誤のご指摘もいただけたこと、重ねて感謝いたします。

**Comment by isawa585** [comment]
@nnnnishi 

量が多いにもかかわらずご確認いただきまして, ありがとうございます.

> (3) 定数とされている量

については, 「パラメータという語も理解しづらい読者」への配慮として「定数」と表現しておられたのですね.

上記も含めて, いただいたご回答内容について, すべて了解しました.
ご対応いただき感謝申し上げます.
