### ISSUE TITLE
第7章の誤植

### ISSUE THREAD

**Issue by isawa585** [ohmsha/PyOptBook#7]
@jiro-iwanaga

第7章 商品推薦のための興味のスコアリング

第1版 第1刷の誤植についてご報告します.

## (1) 誤植

p. 241 図中の文言
誤: 閲覧は同じ日だけれど item2 のほうが多く見ているので ...
正: 閲覧は同じ日だけれど item3 のほうが多く見ているので ...

8月3日に item 3 と item4 を閲覧した回数を比較しているため, item2 は無関係です.

## (2) 誤植

p. 247 上から10行目
誤: 同様に、商品IDが item3 の商品は、頻度 (freq) が3、
正: 同様に、商品IDが item3 の商品は、頻度 (freq) が2、

頻度 (freq) は8月1日から8月3日までに閲覧した総数であるので, 8月4日の閲覧数 (1 pv) を含めない(加算しない)と思います.

なお, p. 248 以降は目を通しておりません.

ご検討いただけると幸いです. よろしくお願いします.

**Comment by jiro-iwanaga** [comment]
@isawa585 
7章の誤植についてご連絡いただきありがとうございます。
ご指摘について第１版第２刷で確認し、全て誤植であることを確認し、さっそく[正誤表](https://github.com/ohmsha/PyOptBook/blob/main/%E6%AD%A3%E8%AA%A4%E8%A1%A8.md)に反映しました。

１月末に第３刷が発行されることが決まっており、そこには間に合わせることはできませんが第４刷が決まりましたら反映させていただきたいと思っております。

なお、前回、いただいたご指摘は第１版第3刷で修正させていただきました。
感謝いたします。

**Comment by isawa585** [comment]
@jiro-iwanaga 

正誤表への反映, ありがとうございました.
また増刷の状況, 前回の第3刷への反映についても, 承知しました.
ご対応いただき感謝申し上げます.
