### ISSUE TITLE
推薦図書の誤植

### ISSUE THREAD

**Issue by isawa585** [ohmsha/PyOptBook#8]
@jiro-iwanaga 

何気なく推薦図書のページを見ていたら, また見つけてしまいました.

## (1) 誤植

p. 297 下から2行目

誤: 齋藤正彦『基礎数学 1 線形代数入門』東京大学出版会 (1966)
正: 齋藤正彦『[基礎数学 1 線型代数入門](https://www.amazon.co.jp/dp/4130620010/)』東京大学出版会 (1966)

齋藤正彦先生の著書では, 「線形」ではなく「線型」と表記されています.

## (2) 誤植

p. 297 下から1行目

誤: 齋藤正彦『基礎数学 4 線形代数演習』東京大学出版会 (1985)
正: 齋藤正彦『[基礎数学 4 線型代数演習](https://www.amazon.co.jp/dp/4130620258/)』東京大学出版会 (1985)

ご検討いただけますと幸いです. よろしくお願いします.

**Comment by jiro-iwanaga** [comment]
@isawa585 
ご連絡ありがとうございます。

齋藤先生が「線形」ではなく「線型」派であることは知っていたのですが、大事な字に誤植を入れてしまったのは不覚です。
さっそく正誤表に反映しました。

ご指摘いただきありがとうございます！

**Comment by isawa585** [comment]
こちらも正誤表への反映, ありがとうございました. いま確認しました.

私の PC でも, ふだんは「線形代数」と変換される設定になっております : )
