### ISSUE TITLE
第5章 165-168のコードについて

### ISSUE THREAD

**Issue by h-m-i-u-r-a** [ohmsha/PyOptBook#9]

**Comment by h-m-i-u-r-a** [comment]
@kotaishr  さま，
ありがとうございます．
どのように小生の書き込みが公開されるのかを含めてgithubの使い方詳細分からず，書き込んだものを消去してしまったのですが届いていたのですね．これまでに小生のやった作業については以下の通りです．

・すべてのcondaのパッケージを最新にして試してみました．変化なし．処理が終わらず警告も出ます．
・(実は内容を書き込む前に)pandasのバージョンダウンをしてやってみたところ，おっしゃる通り警告は出ませんでしたが，処理が終わらないというのに変化はありませんでした．
・ｐ．165-168のコードは3つのdefから始まる関数からできているようですが，ばらばらに実行してみたところ最初の2つはすぐ終わりました．最後3つ目がどうやらうまくいかないようです．

・10分ほど待っていて終わらないと判断したのですがもう少し待ったほうがよいのでしょうか．
小生の conda listの出力をファイル添付いたします．
なにとぞお助けいただきたくよろしくお願いいたします．







[condalist.txt](https://github.com/ohmsha/PyOptBook/files/8218863/condalist.txt)

**Comment by h-m-i-u-r-a** [comment]
kotaishrさま，
再度実行してみたところ，今度は15分ほど時間がかかりましたがうまくできました．お騒がせいたしました．

h-m-i-u-r-a

**Comment by kotaishr** [comment]
状況のご共有ありがとうございます！
